frlnc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from frlnc import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('buyer/', views.buyer_page, name='buyer'),
    path('seller/', views.seller_page, name='seller'),
    path('create_order/', views.CreateOrder.as_view(), name='create_order'),
    path('', views.index, name='index'),
    path('order_detail/<int:pk>', views.order_detail, name='order_detail'),
    path('order_edit/<int:pk>', views.OrderEdit.as_view(), name='order_edit'),
    path('order_action/<int:pk>', views.OrderAction.as_view(), name='order_action'),
    path('search_results/', views.search_results, name='search_results'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('profile/<slug:username>', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('edit_profile/', views.ProfileEdit.as_view(), name='edit_profile'),
    path('find_workers/', views.find_workers, name='find_workers'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    class ProfessionChoices(models.TextChoices):
        pd = ('python', 'Python-разработчик')
        jd = ('java', 'Java-разработчик')
        sql = ('sql', 'Архитектор баз данных')
        analytic = ('analytic', 'Аналитик')
        phpd = ('php', 'PHP-разработчик')
        cd = ('c', 'C-разработчик')
    gender_choices = (
        ('m', 'Мужчина'),
        ('f', 'Женщина'),
    )
    avatar = models.ImageField(upload_to='avatars', default='avatars/default.png')
    first_name = models.CharField("first name", max_length=30)
    last_name = models.CharField("last name", max_length=30)
    email = models.EmailField("email")
    gender = models.CharField("gender", max_length=100, choices=gender_choices, default='m')
    profession = models.CharField('profession', max_length=100, blank=True, default='', choices=ProfessionChoices.choices)
    exp = models.CharField('exp', blank=True, max_length=100, default=0)
    about = models.TextField("about", default='', max_length=100, blank=True)
    telegram = models.CharField("tg", max_length=64, default='', blank=True)
    vk = models.URLField("vk", default='', blank=True)

    REQUIRED_FIELDS = ["email", "first_name", "last_name", "gender", "profession"]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegisterForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'profession', 'gender', 'first_name', 'last_name')


class ChangeProfileForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('avatar', 'email', 'exp', 'telegram', 'vk', 'about',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import CustomUser
from .forms import RegisterForm, ChangeProfileForm



class Register(View):
    template_name = 'users/register.html'

    def get(self, request):
        form = RegisterForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        else:
            return render(request, self.template_name, {'form': form})

def profile(request, username):
    if not request.user.is_authenticated and username != 'AnonymousUser' or request.user.is_authenticated:
        user = CustomUser.objects.get(username=username)
        return render(request, 'users/profile.html', {'user_info': user})
    else:
        return redirect('login')


def find_workers(request):
    form = RegisterForm()
    profession = request.GET.get('profession')
    if profession is None or profession == '':
        workers = CustomUser.objects.all()
        return render(request, 'users/find_workers.html', {'workers': workers, 'form': form})
    workers = CustomUser.objects.filter(profession=profession)
    return render(request, 'users/find_workers.html', {'workers': workers, 'form': form})


class ProfileEdit(LoginRequiredMixin, View):
    template_name = 'users/edit_profile.html'

    def get(self, request):
        profile = get_object_or_404(CustomUser, id=request.user.id)
        form = ChangeProfileForm(instance=profile)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        profile = get_object_or_404(CustomUser, id=request.user.id)
        form = ChangeProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile', username=request.user.username)
        return render(request, self.template_name, {'form': form})

users/templates/users/edit_profile.html
{% extends 'main/base.html' %}

{% block content %}
<form enctype="multipart/form-data" method="POST">{% csrf_token %}
        <p>Выбрать аватарку: {{ form.avatar }}</p>
        <p>Почта: {{ form.email }}</p>
        <p>Опыт работы: {{ form.exp }}</p>
        <p>Телеграм: {{ form.telegram }}</p>
        <p>Вконтакте: {{ form.vk }}</p>
        <p>Про себя: {{ form.about }}</p>
        <button type="submit">Сохранить</button>
</form>
{% endblock %}

users/templates/users/find_workers.html
{% extends 'main/base.html' %}

{% block content %}
<form action="{% url 'find_workers' %}" method="get">
    <p>Выберите профессию: {{ form.profession }}</p>
    <input type="submit" value="Искать"/>
</form>
    {% for worker in workers %}
        <div class="blocks">
            <h2><a href="{% url 'profile' username=worker.username %}">Исполнитель: {{ worker.username }}</a></h2>
            <h3>Профессия: {{ worker.get_profession_display }}</h3>
        </div>
    {% endfor %}
{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">{% csrf_token %}
        <p>Имя пользователя: {{ form.username }}</p>
        <p>Пароль: {{ form.password }}</p>
        <p>{{ form.non_field_errors }}</p>
        <button type="submit" class="save btn btn-default">Войти</button>
</form>
<a href="{% url 'register' %}">Если нет профиля - зарегистрируйтесь</a>
</body>
</html>

users/templates/users/logout.html
{% extends 'main/base.html' %}

{% block content %}
<p>Вы вышли из системы</p>
<a href="{% url 'index' %}">Вы можете вернуться на главную страницу</a>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="avatar">
        <img src="{{ user_info.avatar.url }}" width="340" height="280" alt="ava">
    </div>
    <div class="profile">
        <h1>Профиль {{ user_info.username }}</h1>
        <p>Имя: {{ user_info.first_name }}</p>
        <p>Фамилия: {{ user_info.last_name }}</p>
        <p>Пол: {{ user_info.get_gender_display }}</p>
        <p>Дата регистрации: {{ user_info.date_joined }}</p>
        <p>Почта: {{ user_info.email }}</p>
        <p>Профессия: {{ user_info.get_profession_display }}</p>
        <p>Опыт работы (в годах): {{ user.exp }}</p>
        <p>Телеграм: {{ user_info.telegram }}</p>
        <p>Вконтакте: <a href="{{ user_info.vk }}">{{ user_info.vk }}</a></p>
        <p>Про себя: {{ user_info.about }}</p>
        <button type="button"><a href="{% url 'edit_profile' %}">Редактировать профиль</a></button>
        <button type="button"><a href="{% url 'logout' %}">Выйти</a></button>
    </div>
{% endblock %}

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">{% csrf_token %}
    <p>Имя пользователя: {{ form.username }}</p>
    <p>Почта: {{ form.email }}</p>
    <p>Пол: {{ form.gender }}</p>
    <p>Имя: {{ form.first_name }}</p>
    <p>Фамилия: {{ form.last_name }}</p>
    <p>Ваша профессия: {{ form.profession }}</p>
    <p>Пароль: {{ form.password1}}</p>
    <p>Пароль еще раз: {{ form.password2 }}</p>
    <button type="submit" class="save btn btn-default">Зарегистрироваться</button>
    <p>{{ form.errors }}</p>
</form>
<a href="{% url 'login' %}">Есть профиль? Войдите</a>
</body>
</html>