frlnc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from frlnc import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('buyer/', views.buyer_page, name='buyer'),
    path('seller/', views.seller_page, name='seller'),
    path('create_order/', views.CreateOrder.as_view(), name='create_order'),
    path('', views.index, name='index'),
    path('order_detail/<int:pk>', views.order_detail, name='order_detail'),
    path('order_edit/<int:pk>', views.OrderEdit.as_view(), name='order_edit'),
    path('order_action/<int:pk>', views.OrderAction.as_view(), name='order_action'),
    path('search_results/', views.search_results, name='search_results'),
]

main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from frlnc.settings import AUTH_USER_MODEL


class Order(models.Model):
    class ProfessionChoices(models.TextChoices):
        pd = ('python', 'Python-разработчик')
        jd = ('java', 'Java-разработчик')
        sql = ('sql', 'Архитектор баз данных')
        analytic = ('analytic', 'Аналитик')
        phpd = ('php', 'PHP-разработчик')
        cd = ('c', 'C-разработчик')
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    who_needs = models.CharField(max_length=100, choices=ProfessionChoices.choices)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=512)
    price = models.IntegerField()

    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    orders = models.ManyToManyField(Order, related_name='orders')  # проекты, то есть задания, которые ты выкладываешь
    offers = models.ManyToManyField(Order, related_name='offers')  # задания, которые ты взял выполнять как исполнитель

    @receiver(post_save, sender=AUTH_USER_MODEL)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    def __str__(self):
        return self.user.__str__()

main/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('title', 'description', 'price', 'who_needs')

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import OrderForm
from .models import Order, Profile


def index(request):
    orders = Order.objects.all()
    form = OrderForm()
    return render(request, 'main/index.html', {'orders': orders, 'form': form})


def order_detail(request, pk):
    if not request.user.is_authenticated:
        order = get_object_or_404(Order, pk=pk)
        return render(request, 'main/order_detail.html', {'order': order})
    else:
        order = get_object_or_404(Order, pk=pk)
        user_offers = Profile.objects.get(user=request.user).offers.all()
        return render(request, 'main/order_detail.html', {'order': order, 'user_offers': user_offers})


def search_results(request):
    query = request.GET.get('orders')
    prof = request.GET.get('who_needs')
    form = OrderForm()
    orders = Order.objects.filter(title__contains=query, who_needs=prof)
    return render(request, 'main/index.html', {'orders': orders, 'form': form})


@login_required
def buyer_page(request):
    user_orders = Profile.objects.get(user=request.user).orders.all()
    return render(request, 'main/buyer_page.html', {'orders': user_orders})


@login_required
def seller_page(request):
    user_offers = Profile.objects.get(user=request.user).offers.all()
    return render(request, 'main/seller_page.html', {'offers': user_offers})


class OrderAction(LoginRequiredMixin, View):

    def get(self, request, pk):
        return redirect('order_detail', pk=pk)

    def post(self, request, pk):
        user_profile = Profile.objects.get(user=request.user)
        order = Order.objects.get(pk=pk)
        data = request.POST
        action = data.get('order')
        print(action)
        if action == 'delete':
            user_offers = user_profile.offers.all()
            if request.user != order.author:
                if order not in user_offers:
                    return redirect('index')
                else:
                    order.delete()
                    return redirect('buyer')
            order.delete()
            return redirect('buyer')
        elif action == 'add':
            if request.user == order.author:
                return redirect('buyer')
            else:
                user_profile.offers.add(order)
                return redirect('seller')
        elif action == 'cancel':
            user_profile.offers.remove(order)
            return redirect('seller')
        return redirect('order_detail', pk=pk)


class CreateOrder(LoginRequiredMixin, View):
    template_name = 'main/create_order.html'

    def get(self, request):
        form = OrderForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.author = request.user
            order.save()
            author_profile = Profile.objects.get(user=order.author)
            author_profile.orders.add(order)
            return redirect('buyer')
        form = OrderForm()
        return render(request, self.template_name, {'form': form})


class OrderEdit(LoginRequiredMixin, View):
    template_name = 'main/order_edit.html'

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        form = OrderForm(instance=order)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            order = form.save(commit=False)
            order.author = request.user
            order.save()
            return redirect('order_detail', pk=pk)
        return render(request, self.template_name, {'form': form})

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Kwork</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'find_workers' %}">Найти исполнителей</a></li>
            <li><a href="{% url 'buyer' %}">Кабинет заказчика</a></li>
            <li><a href="{% url 'seller' %}">Кабинет исполнителя</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'profile' username=request.user %}">Профиль {{ request.user }}</a></li>
                {% if request.user.is_staff %}
                    <li><a href="/admin/">Админ панель</a></li>
                {% endif %}
            {% else %}
                <li><a href="{% url 'profile' username=request.user %}">Вы не авторизованы, нажмите, чтобы войти</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/buyer_page.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Ваши проекты:</h1>
<button type="submit"><a href="{% url 'create_order' %}">Создать новый проект</a></button>
{% for order in orders %}
    <div class="blocks">
        <h2><a href="{% url 'order_detail' pk=order.pk %}">Название: {{ order.title }}</a></h2>
        <h3>Оплата: {{ order.price }}</h3>
    </div>
{% endfor %}
{% endblock %}

main/templates/main/create_order.html
{% extends 'main/base.html' %}

{% block content %}
<form method="POST">{% csrf_token %}
        <p>Название заказа: {{ form.title }}</p>
        <p>Кто требуется: {{ form.who_needs }}</p>
        <p>Описание заказа: {{ form.description }}</p>
        <p>Оплата: {{ form.price }}</p>
        <button type="submit">Создать заказ</button>
</form>
{{ form.errors }}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<form action="{% url 'search_results' %}" method="get">
    <input type="text" name="orders" placeholder="Поиск по названию заказа">
    {{ form.who_needs }}
    <input type="submit" value="Submit!"/>
</form>
<h1>Все заказы:</h1>
{% for order in orders %}
    <div class="blocks">
        <h2><a href="{% url 'order_detail' pk=order.pk %}">Заказ: {{ order.title }}</a></h2>
        <h3>Кто требуется: {{ order.get_who_needs_display }}</h3>
        <h4>Оплата: {{ order.price }}</h4>
        <h5>Автор: <a href="{% url 'profile' username=order.author %}">{{ order.author }}</a></h5>
    </div>
{% endfor %}
{% endblock %}

main/templates/main/order_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="detail">
    <h1>Заказ: {{ order.title}}</h1>
    <p>Кто требуется: {{ order.get_who_needs_display }}</p>
    <p>Описание к заказу: {{ order.description }}</p>
    <p>Оплата за выполненный заказ: {{ order.price }}</p>
    <p>Автор: <a href="{% url 'profile' username=order.author %}">{{ order.author }}</a></p>
    <form method="post" action="{% url 'order_action' pk=order.pk %}"> {% csrf_token %}
        {% if order.author == request.user %}
            <button type="button"><a href="{% url 'order_edit' pk=order.pk %}">Редактировать</a></button>
            <button type="submit" name="order" value="delete">Удалить</button>
        {% elif order in user_offers %}
            <button type="submit" name="order" value="cancel">Отказаться</button>
            <button type="submit" name="order" value="delete">Выполнено</button>
        {% else %}
            <button type="submit" name="order" value="add">Взять заказ</button>
        {% endif %}
    </form>
</div>
{% endblock %}

main/templates/main/order_edit.html
{% extends 'main/base.html' %}

{% block content %}
<form method="POST">{% csrf_token %}
        <div>
                <p>Название: {{ form.title }}</p>
                <p>Описание: {{ form.description }}</p>
                <p>Оплата: {{ form.price }}</p>
                <button type="submit">Сохранить</button>
        </div>
</form>
{% endblock %}

main/templates/main/seller_page.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Ваши текущие взятые заказы:</h1>
{% for offer in offers %}
    <div class="blocks">
        <h2><a href="{% url 'order_detail' pk=offer.pk %}">Название: {{ offer.title }}</a></h2>
        <h3>Оплата: {{ offer.price }}</h3>
        <h4>Автор: <a href="{% url 'profile' username=offer.author %}">{{ offer.author }}</a></h4>
    </div>
{% endfor %}
{% endblock %}